version: '3.7'
services:
  proyectos-apirest:
    container_name: proyectos-apirest
    image : proyectos-apirest:v1
    build:
      context: .
    ports:
      - "4000:4000"
    networks:
      - proyectos-app
networks: 
  proyectos-app:
